=== microscopexyz/chainmetareader/chainmeta_reader/meta_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ChainMeta",
    "description": "An object designed to uniformly describe blockchain metadata from different providers",
    "type": "object",
    "required": [
        "community",
        "provider",
        "version",
        "revision",
        "introduction",
        "chainmetadata"
    ],
    "properties": {
        "community": {
            "description": "The community name of this open source project",
            "type": "string",
            "enum": [
                "openchainmeta"
            ]
        },
        "provider": {
            "description": "Basic information of the data provider",
            "type": "object",
            "required": [
                "provider_name",
                "provider_id",
                "provider_signature"
            ],
            "properties": {
                "provider_name": {
                    "description": "Provider's name",
                    "type": "string"
                },
                "provider_id": {
                    "description": "Provider's unique id",
                    "type": "string",
                    "pattern": "^ocm[0-9]{6}$"
                },
                "provider_signature": {
                    "description": "Provider's signature",
                    "type": "string"
                }
            }
        },
        "version": {
            "description": "The version of provider's metadata",
            "type": "string"
        },
        "revision": {
            "description": "The revision of provider's metadata",
            "type": "integer"
        },
        "introduction": {
            "description": "Introduction of provider's metadata",
            "type": "string",
            "format": "uri"
        },
        "chainmetadata": {
            "description": "Details of provider's metadata",
            "type": "object",
            "required": [
                "schema",
                "artifact"
            ],
            "properties": {
                "schema": {
                    "description": "Schema of provider's metadata, explain how data is read",
                    "type": "string",
                    "format": "uri"
                },
                "artifact": {
                    "description": "Storage details of provider's metadata",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "required": [
                            "artifact_type",
                            "path",
                            "fileformat",
                            "signature"
                        ],
                        "properties": {
                            "artifact_type": {
                                "description": "Type of artifact",
                                "type": "string",
                                "enum": [
                                    "oss",
                                    "remote path"
                                ]
                            },
                            "path": {
                                "description": "Path of the metadata file",
                                "type": "string",
                                "format": "uri"
                            },
                            "fileformat": {
                                "description": "Format of the metadata file",
                                "type": "string",
                                "enum": [
                                    "json",
                                    "parquet",
                                    "csv"
                                ]
                            },
                            "signature": {
                                "description": "Signature of the metadata file",
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== microscopexyz/chainmetareader/examples/chaintool_meta.json
{
    "community": "openchainmeta",
    "provider": {
        "provider_name": "chaintool",
        "provider_id": "ocm000001",
        "provider_signature": "xxxxx"
    },
    "version": "v1",
    "revision": 1,
    "introduction": "https://github.com/openchainmeta/chainmetareader/doc/chaintool/introduction.md",
    "chainmetadata": {
        "schema": "https://github.com/openchainmeta/chainmetareader/doc/chaintool/schema.md",
        "artifact": [{
                "artifact_type": "oss",
                "path": "xxxxx",
                "fileformat": "parquet",
                "signature": "xxxxx",
                "access_id": "xxxxx",
                "access_key": "xxxxx",
                "bucket": "xxxxx",
                "endpoint": "xxxxx"
            }
        ]
    }
}

=== microscopexyz/chainmetareader/tests/data/chaintool_meta.json
{
    "community": "openchainmeta",
    "provider": {
        "provider_name": "chaintool",
        "provider_id": "ocm000001",
        "provider_signature": "xxxxx"
    },
    "version": "v1",
    "revision": 1,
    "introduction": "https://github.com/openchainmeta/chainmetareader/doc/chaintool/introduction.md",
    "chainmetadata": {
        "schema": "https://github.com/openchainmeta/chainmetareader/doc/chaintool/schema.md",
        "artifact": [{
                "artifact_type": "remote path",
                "path": "https://github.com/openchainmeta/chainmetareader/blob/add_chaintool_metadata/examples/chaintool_sample_100.csv",
                "fileformat": "csv",
                "signature": "e3aeb7c8f63d29fda476f7f96d9417ee"
            }
        ]
    }
}
