=== microscopexyz/chainmetareader/chainmeta_reader/schema/artifact_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ChainMeta Artifact",
    "description": "An object designed to uniformly describe blockchain metadata artifacts from different providers",
    "type": "array",
    "items": {
        "description": "",
        "type": "object",
        "required": [
            "chain",
            "address",
            "entity",
            "categories",
            "source",
            "submitted_by",
            "submitted_on"
        ],
        "properties": {
            "chain": {
                "$ref": "/schemas/chain"
            },
            "address": {
                "$ref": "/schemas/address"
            },
            "entity": {
                "$ref": "/schemas/entity"
            },
            "name": {
                "type": "string"
            },
            "categories": {
                "type": "array",
                "items": {
                    "$ref": "/schemas/category"
                }
            },
            "source": {
                "$ref": "/schemas/source"
            },
            "submitted_by": {
                "type": "string"
            },
            "submitted_on": {
                "type": "string",
                "format": "date"
            }
        },
        "additionalProperties": false
    },
    "$defs": {
        "chain": {
            "$id": "/schemas/chain",
            "type": "chain"
        },
        "address": {
            "$id": "/schemas/address",
            "type": "string"
        },
        "entity": {
            "$id": "/schemas/entity",
            "type": "entity"
        },
        "category": {
            "$id": "/schemas/category",
            "type": "category"
        },
        "source": {
            "$id": "/schemas/source",
            "type": "source"
        }
    }
}

=== microscopexyz/chainmetareader/examples/footprint_artifact_sample.json
[
    {
        "address": "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d",
        "chain": "ethereum_mainnet",
        "entity": "bored-ape-yacht-club",
        "name": "BoredApeYachtClub",
        "categories": [
            "NFT"
        ],
        "source": "ground_truth",
        "submitted_by": "footprint",
        "submitted_on": "2023-12-27 00:00:00"
    },
    {
        "address": "0x00799bbc833d5b168f0410312d2a8fd9e0e3079c",
        "chain": "ethereum_mainnet",
        "entity": "binance",
        "name": "Binance 31",
        "categories": [
            "CEX",
            "Exchange"
        ],
        "source": "ground_truth",
        "submitted_by": "footprint",
        "submitted_on": "2023-12-27 00:00:00"
    },
    {
        "address": "0xaba7161a7fb69c88e16ed9f455ce62b791ee4d03",
        "chain": "ethereum_mainnet",
        "entity": "bored-ape-yacht-club",
        "name": "Bored Ape Yacht Club: Depolyer",
        "categories": [
            "Deployer"
        ],
        "source": "ground_truth",
        "submitted_by": "footprint",
        "submitted_on": "2023-12-27 00:00:00"
    },
    {
        "address": "0xc0a47dfe034b400b47bdad5fecda2621de6c4d95",
        "chain": "ethereum_mainnet",
        "entity": "uniswap",
        "name": "Uniswap: Factory Contract",
        "categories": [
            "Factory Contract"
        ],
        "source": "ground_truth",
        "submitted_by": "footprint",
        "submitted_on": "2023-12-27 00:00:00"
    },
    {
        "address": "0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad",
        "chain": "ethereum_mainnet",
        "entity": "uniswap",
        "name": "Uniswap: Universal Router",
        "categories": [
            "Defi",
            "DEX",
            "Dapp"
        ],
        "source": "ground_truth",
        "submitted_by": "footprint",
        "submitted_on": "2023-12-27 00:00:00"
    },
    {
        "address": "0x0f50d31b3eaefd65236dd3736b863cffa4c63c4e",
        "chain": "ethereum_mainnet",
        "entity": "a16z",
        "name": "a16z",
        "categories": [
            "Company Funds"
        ],
        "source": "ground_truth",
        "submitted_by": "footprint",
        "submitted_on": "2023-12-27 00:00:00"
    },
    {
        "address": "0x0000000000007f150bd6f54c40a34d7c3d5e9f56",
        "chain": "ethereum_mainnet",
        "entity": "mev bot",
        "name": "mev bot",
        "categories": [
            "MEV Bot"
        ],
        "source": "ground_truth",
        "submitted_by": "footprint",
        "submitted_on": "2023-12-27 00:00:00"
    }
]

=== microscopexyz/chainmetareader/tests/data/artifacts/goplus_artifact_sample.json
[
        {
            "address": "0x333f2e9f074de56d3ed6a0518c3d0df418692b63",
            "chain": "ethereum_mainnet",
            "entity": "",
            "name": "",
            "categories": [
                "honeypot",
                "phishing",
                "theft"
            ],
            "source": "ground_truth",
            "submitted_by": "GoPlus",
            "submitted_on": "2023-02-14 16:00:09"
        },
        {
            "address": "0xec117f9066a8ad1caef190372ee7560f04d997dd",
            "chain": "ethereum_mainnet",
            "entity": "",
            "name": "",
            "categories": [
                "honeypot",
                "phishing",
                "high_risk"
            ],
            "source": "ground_truth",
            "submitted_by": "GoPlus",
            "submitted_on": "2023-03-06 06:41:44"
        }
    ]

=== microscopexyz/chainmetareader/tests/data/artifacts/coinbase_artifact_additional_sample.json
[
    {
        "address": "0xf177aa7b0602f787f6f01c65f4b2e267336fd349",
        "chain": "ethereum_mainnet",
        "entity": "uniswap",
        "name": "Uniswap V2: Hmf",
        "categories": [
            "defi",
            "dex"
        ],
        "source": "ground_truth",
        "submitted_by": "coinbase",
        "submitted_on": "2022-09-21 00:00:00"
    },
    {
        "address": "0xd62f1beba129440c5c07e4fb597ec1f61260d26b",
        "chain": "ethereum_mainnet",
        "entity": "uniswap",
        "name": "Uniswap V2: $Ashiba",
        "categories": [
            "defi",
            "dex"
        ],
        "source": "ground_truth",
        "submitted_by": "coinbase",
        "submitted_on": "2022-09-21 00:00:00"
    },
    {
        "address": "0x0db4078fa4fc916fc2b881aca99039ccdde6fa46",
        "chain": "ethereum_mainnet",
        "entity": "binance",
        "name": "Binance",
        "categories": [
            "exchange",
            "no_kyc"
        ],
        "source": "ground_truth",
        "submitted_by": "coinbase",
        "submitted_on": "2022-12-17 00:00:00.000000000"
    },
    {
        "address": "0x1c5db575e2ff833e46a2e9864c22f4b22e0b37c2",
        "chain": "ethereum_mainnet",
        "entity": "ren",
        "name": "Ren: Renzec Token",
        "categories": [
            "bridging",
            "dapp"
        ],
        "source": "ground_truth",
        "submitted_by": "coinbase",
        "submitted_on": "2022-09-21 00:00:00.000000000"
    },
    {
        "address": "0xd5da8cef79c430d337fdb4d7a5b6646132395a86",
        "chain": "ethereum_mainnet",
        "entity": "balancer",
        "name": "Balancer: Safe2/Eth/Cover/Dai/10/40/10",
        "categories": [
            "defi",
            "dex"
        ],
        "source": "ground_truth",
        "submitted_by": "coinbase",
        "submitted_on": "2022-09-21 00:00:00.000000000"
    },
    {
        "address": "0xd5da8cef79c430d337fdb4d7a5b6646132395a86",
        "chain": "ethereum_mainnet",
        "entity": null,
        "name": null,
        "categories": [
            "sanctioned"
        ],
        "source": "ground_truth",
        "submitted_by": "coinbase",
        "submitted_on": "2022-09-21 00:00:00.000000000",
        "additional_metadata": {
            "valid_from": "2022-09-21 00:00:00.000000000",
            "valid_to": "2024-09-21 00:00:00.000000000",
            "reason": "https://xyz.com"
        }
    }
]

=== microscopexyz/chainmetareader/tests/data/artifacts/messari_artifact_sample.json
[
    {
        "address": "0x50c1a2ea0a861a967d9d0ffe2ae4012c2e053804",
        "chain": "ethereum_mainnet",
        "entity": "yearn_finance",
        "name": "Yearn V2 Registry",
        "categories": [
            "defi",
            "yield"
        ],
        "source": "ground_truth",
        "submitted_by": "messari",
        "submitted_on": "2023-01-04 00:00:00"
    },
    {
        "address": "0x93a62da5a14c80f265dabc077fcee437b1a0efde",
        "chain": "ethereum_mainnet",
        "entity": "yearn_finance",
        "name": "Yearn Treasury",
        "categories": [
            "defi",
            "yield"
        ],
        "source": "ground_truth",
        "submitted_by": "messari",
        "submitted_on": "2023-01-04 00:00:00"
    }
]
